curl -X 'POST' \
  'https://api242.onrender.com/auth/login' \
  -H 'accept: */*' \
  -H 'Content-Type: application/json' \
  -d '{
  "username": "hms4@glocation.info",
  "plainpassword": "**test1234test1234"
}'